FROM node:20
# ghcr.io/puppeteer/puppeteer:latest

RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/googlechrome-linux-keyring.gpg \
    && sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/googlechrome-linux-keyring.gpg] https://dl-ssl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-khmeros fonts-kacst fonts-freefont-ttf libxss1 dbus dbus-x11 \
    --no-install-recommends \
    && service dbus start \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /tests
COPY . .

RUN npm ci --omit=dev || npm install --omit=dev

RUN mkdir -p screenshots 
# && chown -R pptruser:pptruser screenshots && chmod -R 0777 screenshots

ENTRYPOINT [ "node", "--max-old-space-size=4096", "./src/index.mjs" ]
