version: '3.8'

name: testing-suite

services:
  e2e-cypress:
    container_name: e2e-cypress
    build:
      context: ./modules/e2e-cypress
      dockerfile: Dockerfile
    deploy:
      resources: # https://docs.cypress.io/guides/getting-started/installing-cypress#System-requirements
        limits:
          cpus: '3' # 2 CPUs minimum to run Cypress, 1 additional CPU if video recording is enabled
          memory: 8G # 4GB minimum, 8GB+ for longer test runs
        reservations:
          cpus: '2'
          memory: 4G
    entrypoint: ["cypress", "run", "--headless", "--browser", "chrome", "--spec", "cypress/e2e/ghost/*.cy.js"] # Override the default entrypoint.
    volumes:
      - ./images/cypress:/tests/cypress/screenshots
      - ./videos/cypress:/tests/cypress/videos
      - ./reports/cypress:/tests/cypress/reports

  e2e-playwright:
    container_name: e2e-playwright
    build:
      context: ./modules/e2e-playwright
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 8G
        reservations:
          cpus: '1'
          memory: 1G
    security_opt:
      - seccomp:./modules/e2e-playwright/seccomp_profile.json
    ipc: host
    # volumes:
    #   - ./images/playwright:/tests/playwright/screenshots
    #   - ./videos/playwright:/tests/playwright/videos
    #   - ./reports/playwright:/tests/playwright/reports