name: testing-suite

services:
  e2e-playwright:
    container_name: e2e-playwright
    image: docker.io/jmgonzalezgarzon/tests-playwright:latest
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    ipc: host
    entrypoint: ["npx", "playwright", "test", "e2e/ghost", "--project", "firefox", "--timeout", "60000"]
    volumes:
      - ./images/playwright:/tests/screenshots
      - ./reports/playwright:/tests/playwright-report
